
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.tesis.util;

/** CUP generated interface containing symbol constants. */
public interface Simbolos {
  /* terminals */
  public static final int parc = 6;
  public static final int fecha = 17;
  public static final int para = 5;
  public static final int preposicion = 13;
  public static final int sustantivo = 15;
  public static final int por = 3;
  public static final int num = 10;
  public static final int proposicion = 14;
  public static final int conjuncion = 16;
  public static final int menor = 9;
  public static final int div = 4;
  public static final int igual = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int mas = 2;
  public static final int adverbio = 12;
  public static final int verbo = 11;
  public static final int adjetivo = 18;
  public static final int mayor = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "por",
  "div",
  "para",
  "parc",
  "igual",
  "mayor",
  "menor",
  "num",
  "verbo",
  "adverbio",
  "preposicion",
  "proposicion",
  "sustantivo",
  "conjuncion",
  "fecha",
  "adjetivo"
  };
}

